<a href="https://colab.research.google.com/github/antonio2505/SuperDataScience_Projects_ML/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [7]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [8]:
tf.__version__

'2.5.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [9]:
dataset = pd.read_csv('Churn_Modelling.csv')

x = dataset.iloc[ : , 3:-1].values
y= dataset.iloc[ : , -1].values

In [10]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [11]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

x[ :, 2] = le.fit_transform(x[ :, 2])

In [13]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')

x = np.array(ct.fit_transform(x))

In [15]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [16]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [17]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [20]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [21]:
ann.add(tf.keras.layers.Dense(units= 6, activation = 'relu'))

### Adding the second hidden layer

In [22]:
ann.add(tf.keras.layers.Dense(units= 6, activation = 'relu'))

### Adding the output layer

In [24]:
ann.add(tf.keras.layers.Dense(units= 1, activation = 'sigmoid'))

## Training the ANN

### Compiling the ANN

In [25]:
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])

### Training the ANN on the Training set

In [26]:
ann.fit(x_train, y_train, batch_size= 32, epochs= 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5967 - accuracy: 0.7190
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4874 - accuracy: 0.7955
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4504 - accuracy: 0.8034
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4332 - accuracy: 0.8099
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4238 - accuracy: 0.8150
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4160 - accuracy: 0.8191
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4071 - accuracy: 0.8216
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3944 - accuracy: 0.8303
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3812 - accuracy: 0.8388
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3716 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [29]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

[[False]]


In [31]:
y_pred = ann.predict(x_test)
y_pred = (y_pred>0.5)

### Making the Confusion Matrix

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1515   80]
 [ 195  210]]


0.8625